import {
  AlertCircle,
  ArrowRight,
  ArrowLeft,
  Users,
  Shuffle,
  LoaderCircle,
  Phone,
  Mail,
  CheckCircle,
  Home,
  Plus,
  Calendar,
  X,
  Menu,
  ChevronDown,
  Star,
  Heart,
  MapPin,
  Clock,
  DollarSign,
  Settings,
  User,
  Search,
  Filter,
  Download,
  Upload,
  Edit,
  Trash2,
  Copy,
  Share2,
  ExternalLink,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Bell,
  BellOff,
  Info,
  HelpCircle,
  Twitter,
  Facebook,
  Instagram,
  Linkedin,
  Briefcase,
  Brain,
  TrendingUp,
  Table,
  Utensils,
  Image,
  Sparkles,
  Send,
  Receipt,
  ArrowDown,
  type LucideIcon,
} from 'lucide-react'

export const iconRegistry = {
  // Core icons
  alertCircle: AlertCircle,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  users: Users,
  shuffle: Shuffle,
  loader: LoaderCircle,
  phone: Phone,
  mail: Mail,
  checkCircle: CheckCircle,
  home: Home,
  plus: Plus,
  calendar: Calendar,
  x: X,
  menu: Menu,
  chevronDown: ChevronDown,
  star: Star,
  heart: Heart,
  mapPin: MapPin,
  clock: Clock,
  dollarSign: DollarSign,
  settings: Settings,
  user: User,
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,
  edit: Edit,
  trash: Trash2,
  copy: Copy,
  share: Share2,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  bell: Bell,
  bellOff: BellOff,
  info: Info,
  help: HelpCircle,
  twitter: Twitter,
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  briefcase: Briefcase,
  brain: Brain,
  trending: TrendingUp,
  table: Table,
  utensils: Utensils,
  image: Image,
  sparkles: Sparkles,
  send: Send,
  receipt: Receipt,
  arrowDown: ArrowDown,
} as const

export type IconName = keyof typeof iconRegistry

export interface IconProps {
  name: IconName
  className?: string
  size?: number | string
  strokeWidth?: number
}

export function getIcon(name: IconName): LucideIcon {
  return iconRegistry[name]
}